server:
  port: 8084
spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://localhost:5432/andersendb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect


eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false